name: ExtraScenes
main: com.extrascenes.ExtraScenesPlugin
version: 1.0.0
api-version: '1.21'
depend: [ProtocolLib, Citizens]
commands:
  scene:
    description: Core scene command
    usage: /scene [create|edit|play|stop|delete]
permissions:
  extrascenes.use:
    default: op
