package com.extrascenes.scene;

public enum GuiType {
    SCENE_DASHBOARD,
    GROUP_SELECT,
    GROUP_GRID,
    TICK_ACTION,
    TICK_TOOLS,
    EFFECTS_MENU,
    TRACK_SELECT,
    KEYFRAME_LIST,
    ADD_KEYFRAME,
    CAMERA_EDITOR,
    CAMERA_OPTIONS,
    COMMAND_EDITOR,
    MODEL_EDITOR,
    MODEL_TICK_LIST,
    MODEL_LIBRARY,
    MODEL_ENTRY_EDITOR,
    ACTIONBAR_EDITOR,
    SCENE_SETTINGS,
    CONFIRM
}
